set -ex
DIR="`dirname \"$0\"`"

REF=${GITHUB_BASE_REF:-${GITHUB_REF}}
BRANCH=${REF##*/}
REPO_NAME=${GITHUB_REPOSITORY##*/}
IMAGE_DB=${GITHUB_REPOSITORY_OWNER}/dinar:$REPO_NAME-db-$BRANCH
IMAGE_ODOO=${GITHUB_REPOSITORY_OWNER}/dinar:$REPO_NAME-odoo-$BRANCH
IMAGE_ODOO_BASE=$IMAGE_ODOO-base
REGISTRY=ghcr.io
REGISTRY_USERNAME="${GITHUB_ACTOR}"
REGISTRY_PASSWORD="$1"

ODOO_VERSION="$(echo $BRANCH | python $DIR/branch2odoo_version.py)"
echo "ODOO_VERSION=$ODOO_VERSION"

echo "DB_VERSION=10" >> $GITHUB_ENV
echo "ODOO_VERSION=$ODOO_VERSION" >> $GITHUB_ENV
echo "IMAGE_DB=$IMAGE_DB" >> $GITHUB_ENV
echo "IMAGE_ODOO=$IMAGE_ODOO" >> $GITHUB_ENV
echo "IMAGE_ODOO_BASE=$IMAGE_ODOO_BASE" >> $GITHUB_ENV
echo "REGISTRY=${REGISTRY}" >> $GITHUB_ENV
echo "REGISTRY_USERNAME=${REGISTRY_USERNAME}" >> $GITHUB_ENV
echo "REGISTRY_PASSWORD=${REGISTRY_PASSWORD}" >> $GITHUB_ENV

# authenticate
if [ ! -z "$REGISTRY_PASSWORD" ]; then
    echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USERNAME" --password-stdin "$REGISTRY"
fi
